# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-12 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_auto_20171212_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeleavemaster',
            name='vacationLeavesLeft',
        ),
    ]
