# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-12 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_remove_employeeleavemaster_vacationleavesleft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeleavemaster',
            name='maternityLeavesLeft',
        ),
        migrations.RemoveField(
            model_name='employeeleavemaster',
            name='work_from_home_availed',
        ),
    ]
