# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-12 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_auto_20171212_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleavemaster',
            name='VacationLeavesLeft',
            field=models.FloatField(default=0),
        ),
    ]
