# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-18 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_employeeleavemaster_vacationleavesleft'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logincredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpID', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
    ]
